<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBCountBySystemAndNameBean extends BaseBean {
	public function __construct() {
		
		$this->_map["Count"] = "count";
		$this->_aliases["count"] = "int";
	}


	/**
	 * @var int
	 */
    private $_varCount;

	/**
	 * @return int
	 */
	public function getCount() {
		return $this->_varCount;
	}

	/**
	 * @param string $value
	 * @return DBCountBySystemAndNameBean
	 */
	public function setCount($value) {
		$this->_varCount = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
	}
	
}