<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBFactionsBean extends BaseBean {
	public function __construct() {
		
		$this->_map["FactionId"] = "faction_id";
		$this->_map["FactionNameLower"] = "faction_name_lower";
		$this->_map["FactionName"] = "faction_name";
		$this->_aliases["faction_id"] = "int";
		$this->_aliases["faction_name_lower"] = "string";
		$this->_aliases["faction_name"] = "string";
	}


	/**
	 * @var int
	 */
    private $_varFactionId;

	/**
	 * @return int
	 */
	public function getFactionId() {
		return $this->_varFactionId;
	}

	/**
	 * @param string $value
	 * @return DBFactionsBean
	 */
	public function setFactionId($value) {
		$this->_varFactionId = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varFactionNameLower;

	/**
	 * @return string
	 */
	public function getFactionNameLower() {
		return $this->_varFactionNameLower;
	}

	/**
	 * @param string $value
	 * @return DBFactionsBean
	 */
	public function setFactionNameLower($value) {
		$this->_varFactionNameLower = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varFactionName;

	/**
	 * @return string
	 */
	public function getFactionName() {
		return $this->_varFactionName;
	}

	/**
	 * @param string $value
	 * @return DBFactionsBean
	 */
	public function setFactionName($value) {
		$this->_varFactionName = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
		$this->setFactionId($value);
		
	}
	
}