<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBSettlementsSearchBean extends BaseBean {
	public function __construct() {
		
		$this->_map["Planet"] = "planet";
		$this->_map["SettlementTypeId"] = "settlement_type_id";
		$this->_map["SettlementId"] = "settlement_id";
		$this->_map["Name"] = "name";
		$this->_map["Title"] = "title";
		$this->_map["X"] = "x";
		$this->_map["Y"] = "y";
		$this->_map["SystemName"] = "system_name";
		$this->_map["Z"] = "z";
		$this->_map["SystemId"] = "system_id";
		$this->_aliases["planet"] = "string";
		$this->_aliases["settlement_type_id"] = "int";
		$this->_aliases["settlement_id"] = "int";
		$this->_aliases["name"] = "string";
		$this->_aliases["title"] = "string";
		$this->_aliases["x"] = "double";
		$this->_aliases["y"] = "double";
		$this->_aliases["system_name"] = "string";
		$this->_aliases["z"] = "double";
		$this->_aliases["system_id"] = "int";
	}


	/**
	 * @var string
	 */
    private $_varPlanet;

	/**
	 * @return string
	 */
	public function getPlanet() {
		return $this->_varPlanet;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setPlanet($value) {
		$this->_varPlanet = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSettlementTypeId;

	/**
	 * @return int
	 */
	public function getSettlementTypeId() {
		return $this->_varSettlementTypeId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setSettlementTypeId($value) {
		$this->_varSettlementTypeId = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSettlementId;

	/**
	 * @return int
	 */
	public function getSettlementId() {
		return $this->_varSettlementId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setSettlementId($value) {
		$this->_varSettlementId = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varName;

	/**
	 * @return string
	 */
	public function getName() {
		return $this->_varName;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setName($value) {
		$this->_varName = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varTitle;

	/**
	 * @return string
	 */
	public function getTitle() {
		return $this->_varTitle;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setTitle($value) {
		$this->_varTitle = $value;
		return $this;
	}
	

	/**
	 * @var double
	 */
    private $_varX;

	/**
	 * @return double
	 */
	public function getX() {
		return $this->_varX;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setX($value) {
		$this->_varX = $value;
		return $this;
	}
	

	/**
	 * @var double
	 */
    private $_varY;

	/**
	 * @return double
	 */
	public function getY() {
		return $this->_varY;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setY($value) {
		$this->_varY = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varSystemName;

	/**
	 * @return string
	 */
	public function getSystemName() {
		return $this->_varSystemName;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setSystemName($value) {
		$this->_varSystemName = $value;
		return $this;
	}
	

	/**
	 * @var double
	 */
    private $_varZ;

	/**
	 * @return double
	 */
	public function getZ() {
		return $this->_varZ;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setZ($value) {
		$this->_varZ = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSystemId;

	/**
	 * @return int
	 */
	public function getSystemId() {
		return $this->_varSystemId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsSearchBean
	 */
	public function setSystemId($value) {
		$this->_varSystemId = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
		$this->setSettlementId($value);
		
	}
	
}