<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBSettlementTypesBean extends BaseBean {
	public function __construct() {
		
		$this->_map["SettlementTypeId"] = "settlement_type_id";
		$this->_map["Title"] = "title";
		$this->_map["Type"] = "type";
		$this->_map["Group"] = "group";
		$this->_aliases["settlement_type_id"] = "int";
		$this->_aliases["title"] = "string";
		$this->_aliases["type"] = "string";
		$this->_aliases["group"] = "string";
	}


	/**
	 * @var int
	 */
    private $_varSettlementTypeId;

	/**
	 * @return int
	 */
	public function getSettlementTypeId() {
		return $this->_varSettlementTypeId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementTypesBean
	 */
	public function setSettlementTypeId($value) {
		$this->_varSettlementTypeId = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varTitle;

	/**
	 * @return string
	 */
	public function getTitle() {
		return $this->_varTitle;
	}

	/**
	 * @param string $value
	 * @return DBSettlementTypesBean
	 */
	public function setTitle($value) {
		$this->_varTitle = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varType;

	/**
	 * @return string
	 */
	public function getType() {
		return $this->_varType;
	}

	/**
	 * @param string $value
	 * @return DBSettlementTypesBean
	 */
	public function setType($value) {
		$this->_varType = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varGroup;

	/**
	 * @return string
	 */
	public function getGroup() {
		return $this->_varGroup;
	}

	/**
	 * @param string $value
	 * @return DBSettlementTypesBean
	 */
	public function setGroup($value) {
		$this->_varGroup = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
		$this->setSettlementTypeId($value);
		
	}
	
}