<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBSettlementsBean extends BaseBean {
	public function __construct() {
		
		$this->_map["Planet"] = "planet";
		$this->_map["SettlementTypeId"] = "settlement_type_id";
		$this->_map["SettlementId"] = "settlement_id";
		$this->_map["Name"] = "name";
		$this->_map["SystemId"] = "system_id";
		$this->_aliases["planet"] = "string";
		$this->_aliases["settlement_type_id"] = "int";
		$this->_aliases["settlement_id"] = "int";
		$this->_aliases["name"] = "string";
		$this->_aliases["system_id"] = "int";
	}


	/**
	 * @var string
	 */
    private $_varPlanet;

	/**
	 * @return string
	 */
	public function getPlanet() {
		return $this->_varPlanet;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsBean
	 */
	public function setPlanet($value) {
		$this->_varPlanet = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSettlementTypeId;

	/**
	 * @return int
	 */
	public function getSettlementTypeId() {
		return $this->_varSettlementTypeId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsBean
	 */
	public function setSettlementTypeId($value) {
		$this->_varSettlementTypeId = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSettlementId;

	/**
	 * @return int
	 */
	public function getSettlementId() {
		return $this->_varSettlementId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsBean
	 */
	public function setSettlementId($value) {
		$this->_varSettlementId = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varName;

	/**
	 * @return string
	 */
	public function getName() {
		return $this->_varName;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsBean
	 */
	public function setName($value) {
		$this->_varName = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSystemId;

	/**
	 * @return int
	 */
	public function getSystemId() {
		return $this->_varSystemId;
	}

	/**
	 * @param string $value
	 * @return DBSettlementsBean
	 */
	public function setSystemId($value) {
		$this->_varSystemId = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
		$this->setSettlementId($value);
		
	}
	
}