<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBStationsBean extends BaseBean {
	public function __construct() {
		
		$this->_map["HasOutfitting"] = "has_outfitting";
		$this->_map["MaxLandingPadSize"] = "max_landing_pad_size";
		$this->_map["StationId"] = "station_id";
		$this->_map["Faction"] = "faction";
		$this->_map["DistanceToStar"] = "distance_to_star";
		$this->_map["State"] = "state";
		$this->_map["HasRearm"] = "has_rearm";
		$this->_map["IsPlanetary"] = "is_planetary";
		$this->_map["HasDocking"] = "has_docking";
		$this->_map["UpdatedAt"] = "updated_at";
		$this->_map["Allegiance"] = "allegiance";
		$this->_map["HasBlackmarket"] = "has_blackmarket";
		$this->_map["Name"] = "name";
		$this->_map["HasCommodities"] = "has_commodities";
		$this->_map["TypeId"] = "type_id";
		$this->_map["HasRefuel"] = "has_refuel";
		$this->_map["Economies"] = "economies";
		$this->_map["HasShipyard"] = "has_shipyard";
		$this->_map["Type"] = "type";
		$this->_map["Government"] = "government";
		$this->_map["HasRepair"] = "has_repair";
		$this->_map["SystemId"] = "system_id";
		$this->_map["HasMarket"] = "has_market";
		$this->_aliases["has_outfitting"] = "int";
		$this->_aliases["max_landing_pad_size"] = "string";
		$this->_aliases["station_id"] = "int";
		$this->_aliases["faction"] = "int";
		$this->_aliases["distance_to_star"] = "int";
		$this->_aliases["state"] = "string";
		$this->_aliases["has_rearm"] = "int";
		$this->_aliases["is_planetary"] = "int";
		$this->_aliases["has_docking"] = "int";
		$this->_aliases["updated_at"] = "int";
		$this->_aliases["allegiance"] = "string";
		$this->_aliases["has_blackmarket"] = "int";
		$this->_aliases["name"] = "string";
		$this->_aliases["has_commodities"] = "int";
		$this->_aliases["type_id"] = "int";
		$this->_aliases["has_refuel"] = "int";
		$this->_aliases["economies"] = "string";
		$this->_aliases["has_shipyard"] = "int";
		$this->_aliases["type"] = "string";
		$this->_aliases["government"] = "string";
		$this->_aliases["has_repair"] = "int";
		$this->_aliases["system_id"] = "int";
		$this->_aliases["has_market"] = "int";
	}


	/**
	 * @var int
	 */
    private $_varHasOutfitting;

	/**
	 * @return int
	 */
	public function getHasOutfitting() {
		return $this->_varHasOutfitting;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasOutfitting($value) {
		$this->_varHasOutfitting = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varMaxLandingPadSize;

	/**
	 * @return string
	 */
	public function getMaxLandingPadSize() {
		return $this->_varMaxLandingPadSize;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setMaxLandingPadSize($value) {
		$this->_varMaxLandingPadSize = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varStationId;

	/**
	 * @return int
	 */
	public function getStationId() {
		return $this->_varStationId;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setStationId($value) {
		$this->_varStationId = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varFaction;

	/**
	 * @return int
	 */
	public function getFaction() {
		return $this->_varFaction;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setFaction($value) {
		$this->_varFaction = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varDistanceToStar;

	/**
	 * @return int
	 */
	public function getDistanceToStar() {
		return $this->_varDistanceToStar;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setDistanceToStar($value) {
		$this->_varDistanceToStar = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varState;

	/**
	 * @return string
	 */
	public function getState() {
		return $this->_varState;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setState($value) {
		$this->_varState = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasRearm;

	/**
	 * @return int
	 */
	public function getHasRearm() {
		return $this->_varHasRearm;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasRearm($value) {
		$this->_varHasRearm = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varIsPlanetary;

	/**
	 * @return int
	 */
	public function getIsPlanetary() {
		return $this->_varIsPlanetary;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setIsPlanetary($value) {
		$this->_varIsPlanetary = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasDocking;

	/**
	 * @return int
	 */
	public function getHasDocking() {
		return $this->_varHasDocking;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasDocking($value) {
		$this->_varHasDocking = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varUpdatedAt;

	/**
	 * @return int
	 */
	public function getUpdatedAt() {
		return $this->_varUpdatedAt;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setUpdatedAt($value) {
		$this->_varUpdatedAt = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varAllegiance;

	/**
	 * @return string
	 */
	public function getAllegiance() {
		return $this->_varAllegiance;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setAllegiance($value) {
		$this->_varAllegiance = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasBlackmarket;

	/**
	 * @return int
	 */
	public function getHasBlackmarket() {
		return $this->_varHasBlackmarket;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasBlackmarket($value) {
		$this->_varHasBlackmarket = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varName;

	/**
	 * @return string
	 */
	public function getName() {
		return $this->_varName;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setName($value) {
		$this->_varName = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasCommodities;

	/**
	 * @return int
	 */
	public function getHasCommodities() {
		return $this->_varHasCommodities;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasCommodities($value) {
		$this->_varHasCommodities = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varTypeId;

	/**
	 * @return int
	 */
	public function getTypeId() {
		return $this->_varTypeId;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setTypeId($value) {
		$this->_varTypeId = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasRefuel;

	/**
	 * @return int
	 */
	public function getHasRefuel() {
		return $this->_varHasRefuel;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasRefuel($value) {
		$this->_varHasRefuel = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varEconomies;

	/**
	 * @return string
	 */
	public function getEconomies() {
		return $this->_varEconomies;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setEconomies($value) {
		$this->_varEconomies = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasShipyard;

	/**
	 * @return int
	 */
	public function getHasShipyard() {
		return $this->_varHasShipyard;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasShipyard($value) {
		$this->_varHasShipyard = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varType;

	/**
	 * @return string
	 */
	public function getType() {
		return $this->_varType;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setType($value) {
		$this->_varType = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varGovernment;

	/**
	 * @return string
	 */
	public function getGovernment() {
		return $this->_varGovernment;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setGovernment($value) {
		$this->_varGovernment = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasRepair;

	/**
	 * @return int
	 */
	public function getHasRepair() {
		return $this->_varHasRepair;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasRepair($value) {
		$this->_varHasRepair = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSystemId;

	/**
	 * @return int
	 */
	public function getSystemId() {
		return $this->_varSystemId;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setSystemId($value) {
		$this->_varSystemId = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varHasMarket;

	/**
	 * @return int
	 */
	public function getHasMarket() {
		return $this->_varHasMarket;
	}

	/**
	 * @param string $value
	 * @return DBStationsBean
	 */
	public function setHasMarket($value) {
		$this->_varHasMarket = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
	}
	
}