<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBSystemsBean extends BaseBean {
	public function __construct() {
		
		$this->_map["Population"] = "population";
		$this->_map["Faction"] = "faction";
		$this->_map["PowerState"] = "power_state";
		$this->_map["Security"] = "security";
		$this->_map["State"] = "state";
		$this->_map["UpdatedAt"] = "updated_at";
		$this->_map["Allegiance"] = "allegiance";
		$this->_map["Power"] = "power";
		$this->_map["Name"] = "name";
		$this->_map["PrimaryEconomy"] = "primary_economy";
		$this->_map["X"] = "x";
		$this->_map["Y"] = "y";
		$this->_map["NeedsPermit"] = "needs_permit";
		$this->_map["Government"] = "government";
		$this->_map["SimbadRef"] = "simbad_ref";
		$this->_map["Z"] = "z";
		$this->_map["SystemId"] = "system_id";
		$this->_aliases["population"] = "string";
		$this->_aliases["faction"] = "int";
		$this->_aliases["power_state"] = "string";
		$this->_aliases["security"] = "string";
		$this->_aliases["state"] = "string";
		$this->_aliases["updated_at"] = "int";
		$this->_aliases["allegiance"] = "string";
		$this->_aliases["power"] = "string";
		$this->_aliases["name"] = "string";
		$this->_aliases["primary_economy"] = "string";
		$this->_aliases["x"] = "string";
		$this->_aliases["y"] = "string";
		$this->_aliases["needs_permit"] = "int";
		$this->_aliases["government"] = "string";
		$this->_aliases["simbad_ref"] = "string";
		$this->_aliases["z"] = "string";
		$this->_aliases["system_id"] = "int";
	}


	/**
	 * @var string
	 */
    private $_varPopulation;

	/**
	 * @return string
	 */
	public function getPopulation() {
		return $this->_varPopulation;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setPopulation($value) {
		$this->_varPopulation = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varFaction;

	/**
	 * @return int
	 */
	public function getFaction() {
		return $this->_varFaction;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setFaction($value) {
		$this->_varFaction = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varPowerState;

	/**
	 * @return string
	 */
	public function getPowerState() {
		return $this->_varPowerState;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setPowerState($value) {
		$this->_varPowerState = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varSecurity;

	/**
	 * @return string
	 */
	public function getSecurity() {
		return $this->_varSecurity;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setSecurity($value) {
		$this->_varSecurity = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varState;

	/**
	 * @return string
	 */
	public function getState() {
		return $this->_varState;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setState($value) {
		$this->_varState = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varUpdatedAt;

	/**
	 * @return int
	 */
	public function getUpdatedAt() {
		return $this->_varUpdatedAt;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setUpdatedAt($value) {
		$this->_varUpdatedAt = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varAllegiance;

	/**
	 * @return string
	 */
	public function getAllegiance() {
		return $this->_varAllegiance;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setAllegiance($value) {
		$this->_varAllegiance = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varPower;

	/**
	 * @return string
	 */
	public function getPower() {
		return $this->_varPower;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setPower($value) {
		$this->_varPower = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varName;

	/**
	 * @return string
	 */
	public function getName() {
		return $this->_varName;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setName($value) {
		$this->_varName = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varPrimaryEconomy;

	/**
	 * @return string
	 */
	public function getPrimaryEconomy() {
		return $this->_varPrimaryEconomy;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setPrimaryEconomy($value) {
		$this->_varPrimaryEconomy = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varX;

	/**
	 * @return string
	 */
	public function getX() {
		return $this->_varX;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setX($value) {
		$this->_varX = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varY;

	/**
	 * @return string
	 */
	public function getY() {
		return $this->_varY;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setY($value) {
		$this->_varY = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varNeedsPermit;

	/**
	 * @return int
	 */
	public function getNeedsPermit() {
		return $this->_varNeedsPermit;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setNeedsPermit($value) {
		$this->_varNeedsPermit = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varGovernment;

	/**
	 * @return string
	 */
	public function getGovernment() {
		return $this->_varGovernment;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setGovernment($value) {
		$this->_varGovernment = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varSimbadRef;

	/**
	 * @return string
	 */
	public function getSimbadRef() {
		return $this->_varSimbadRef;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setSimbadRef($value) {
		$this->_varSimbadRef = $value;
		return $this;
	}
	

	/**
	 * @var string
	 */
    private $_varZ;

	/**
	 * @return string
	 */
	public function getZ() {
		return $this->_varZ;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setZ($value) {
		$this->_varZ = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSystemId;

	/**
	 * @return int
	 */
	public function getSystemId() {
		return $this->_varSystemId;
	}

	/**
	 * @param string $value
	 * @return DBSystemsBean
	 */
	public function setSystemId($value) {
		$this->_varSystemId = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
	}
	
}