<?php
/**
 *  Autogenerated class
 */

namespace ed\db\beans;

use c3s\db\containers\BaseBean;


class DBSystemsSearchBean extends BaseBean {
	public function __construct() {
		
		$this->_map["Name"] = "name";
		$this->_map["SystemId"] = "system_id";
		$this->_aliases["name"] = "string";
		$this->_aliases["system_id"] = "int";
	}


	/**
	 * @var string
	 */
    private $_varName;

	/**
	 * @return string
	 */
	public function getName() {
		return $this->_varName;
	}

	/**
	 * @param string $value
	 * @return DBSystemsSearchBean
	 */
	public function setName($value) {
		$this->_varName = $value;
		return $this;
	}
	

	/**
	 * @var int
	 */
    private $_varSystemId;

	/**
	 * @return int
	 */
	public function getSystemId() {
		return $this->_varSystemId;
	}

	/**
	 * @param string $value
	 * @return DBSystemsSearchBean
	 */
	public function setSystemId($value) {
		$this->_varSystemId = $value;
		return $this;
	}
	
	public function setAutoincrementField($value) {
		
	}
	
}