<?php
/**
 *  Autogenerated class
 */

namespace ed\db\vectors;


use c3s\lib\dc\XMLVector;
use ed\db\beans\DBSettlementsSearchBean;


class DBSettlementsSearchVector extends XMLVector {
	/**
	 * Enter description here ...
	 * @return DBSettlementsSearchBean
	 */
	protected function getNewElement() {
		$element = new DBSettlementsSearchBean();
		return $element;
	}
	
	/**
	 * Enter description here ...
	 * @return DBSettlementsSearchBean
	 */
	public function offsetGet($offset) {
		return parent::offsetGet($offset);
	}
	
	/**
	 * Enter description here ...
	 * @param $value DBSettlementsSearchBean
	 */
	public function offsetSet($offset, $value) {
		parent::offsetSet($offset, $value);
	}
	
	/**
	 * Enter description here ...
	 * @return DBSettlementsSearchBean
	 */
	public function current() {
		return parent::current();
	}
	
	/**
	 * Enter description here ...
	 * @return DBSettlementsSearchBean
	 */
	public function get($index) {
		return parent::get($index);
	}
	
	/**
	 * Enter description here ...
	 * @param $element DBSettlementsSearchBean
	 */
	public function add($element) {
		parent::add($element);
	}
	
	/**
	 * Enter description here ...
	 * @param $vector DBSettlementsSearchBean
	 */
	public function append($vector) {
		parent::append($vector);
	}
	
	
}