<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output encoding="utf-8" indent="no" method="text"/>
	<xsl:param name="package"/>
	<xsl:template match="/bean_info">
&lt;?php
/**
 *  Autogenerated class
 */
<xsl:variable name="pkg" select="translate($package, '.','\')"/>
namespace <xsl:value-of select="$pkg"/>\vectors;

<xsl:variable name="bean_name">DB<xsl:value-of select="bean/@name"/>Bean</xsl:variable>
use c3s\lib\dc\XMLVector;
use <xsl:value-of select="$pkg"/>\beans\<xsl:value-of select="$bean_name"/>;

<xsl:variable name="class_name">DB<xsl:value-of select="bean/@name"/>Vector</xsl:variable>
class <xsl:value-of select="$class_name"/> extends XMLVector {
	/**
	 * Enter description here ...
	 * @return <xsl:value-of select="$bean_name"/>
	 */
	protected function getNewElement() {
		$element = new DB<xsl:value-of select="bean/@name"/>Bean();
		return $element;
	}
	
	/**
	 * Enter description here ...
	 * @return <xsl:value-of select="$bean_name"/>
	 */
	public function offsetGet($offset) {
		return parent::offsetGet($offset);
	}
	
	/**
	 * Enter description here ...
	 * @param $value <xsl:value-of select="$bean_name"/>
	 */
	public function offsetSet($offset, $value) {
		parent::offsetSet($offset, $value);
	}
	
	/**
	 * Enter description here ...
	 * @return <xsl:value-of select="$bean_name"/>
	 */
	public function current() {
		return parent::current();
	}
	
	/**
	 * Enter description here ...
	 * @return <xsl:value-of select="$bean_name"/>
	 */
	public function get($index) {
		return parent::get($index);
	}
	
	/**
	 * Enter description here ...
	 * @param $element <xsl:value-of select="$bean_name"/>
	 */
	public function add($element) {
		parent::add($element);
	}
	
	/**
	 * Enter description here ...
	 * @param $vector <xsl:value-of select="$bean_name"/>
	 */
	public function append($vector) {
		parent::append($vector);
	}
	
	
}
	</xsl:template>
</xsl:stylesheet>
